services:
  api:
    profiles: ['prod']
    platform: linux/amd64
    image: softvence/vandanakalra-backend:latest
    container_name: ${PACKAGE_NAME}_api
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/${PACKAGE_NAME}_db

      BASE_URL: http://0.0.0.0:3000
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        echo 'üèÅ Waiting for DB...';
        sleep 5;
        npx prisma migrate deploy;
        echo 'üöÄ Starting app...';
        npm run start
      "
    volumes:
      - files-data:/app/uploads
      - temp-data:/app/tmp
      - logs-data:/app/logs

  db:
    profiles: ['dev', 'prod']
    image: postgres:17
    container_name: ${PACKAGE_NAME}_db
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${PACKAGE_NAME}_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5434:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PACKAGE_NAME}_pgadmin
    restart: always
    profiles: ['prod']
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${ADMIN_PASSWORD}
      - SCRIPT_NAME=/pgadmin
    ports:
      - '8123:80'
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  files-data:
  temp-data:
  logs-data:

networks:
  default:
    name: ${PACKAGE_NAME}_network
    labels:
      - 'project=${PACKAGE_NAME}'
